refactor: better name for event-type-specific-application-view
CSCfi/rems pull request #2305
Opened 2020-09-08 12:15 UTC by opqdonut

2020-09-08 12:30 UTC, opqdonut commented
another option:
```
event-type-specific-application-view => application-content-view
calculate-permissions => application-permission-view
```

2020-09-09 11:04 UTC, marharyta approved these changes

2020-09-11 09:51 UTC, Macroz requested changes
I think `misc` sounds too much like unimportant. `state` too vague and perhaps conflicts with `application/state`. I think I would like `application-base-view` more.

2020-09-11 09:54 UTC, opqdonut commented
base sounds good :+1:

2020-09-15 06:13 UTC, Macroz approved these changes

2020-09-15 06:55 UTC, merged