Feat 2346
CSCfi/rems pull request #2394
Opened 2020-10-06 12:34 UTC by marharyta

# Definition of Done / Review checklist

## Reviewability
- [ ] link to issue
- [ ] note if PR is on top of other PR
- [ ] note if related change in rems-deploy repo
- [ ] consider adding screenshots for ease of review

## API
- [ ] API is documented and shows up in Swagger UI
- [ ] API is backwards compatible or completely new
- [ ] Events are backwards compatible

## Documentation
- [ ] update changelog if necessary
- [ ] add or update docstrings for namespaces and functions
- [ ] components are added to guide page
- [ ] documentation _at least_ for config options (i.e. docs folder)
- [ ] ADR for major architectural decisions or experiments

## Different installations
- [ ] new configuration options added to rems-deploy repository
- [ ] instance specific translations (i.e. LBR kielivara)

## Testing
- [ ] complex logic is unit tested
- [ ] valuable features are integration / browser / acceptance tested automatically

## Accessibility
- [ ] all icons have the aria-label attribute
- [ ] all fields have a label
- [ ] errors are linked to fields with aria-describedby
- [ ] contrast is checked
- [ ] conscious decision about where to move focus after an action

## Follow-up
- [ ] new tasks are created for pending or remaining tasks
- [ ] no critical TODOs left to implement

2020-10-20 11:00 UTC, Macroz requested changes
Found some small things to consider. I think we can simplify a bit.

2020-10-20 11:07 UTC, marharyta commented on test/clj/rems/test_browser.clj
> +          (btu/click-el (first buttons))
agreed

2020-10-20 11:08 UTC, marharyta commented on test/clj/rems/test_browser.clj
> +        (btu/wait-visible {:tag :h1 :fn/has-text "Form"})))
this works well with visual browser but fails sometimes with headless browser

2020-10-20 11:13 UTC, marharyta commented on test/clj/rems/test_browser.clj
> +        (is (=
Ok, I will run cljfmt

2020-10-20 11:13 UTC, marharyta commented on test/clj/rems/test_browser.clj
> +        ;; (btu/scroll-and-click :fields-0-type-label)
yes, this is a small 'memo' to nit forget it after i implement tests and re-run it

2020-10-20 11:15 UTC, marharyta commented on test/clj/rems/test_browser.clj
> +        (btu/visible? {:tag :div :class :alert-danger :fn/has-text "Submission failed."})
well, the way I see it it validates the error message on a field being empty, how does it "complicate" the code?

2020-10-20 11:15 UTC, marharyta commented on test/clj/rems/test_browser.clj
> +          (btu/click-el (first buttons))
Good point!

2020-10-20 11:34 UTC, Macroz commented on test/clj/rems/test_browser.clj
> +        (btu/visible? {:tag :div :class :alert-danger :fn/has-text "Submission failed."})
Well the reasoning is shortly: more code = more bugs, test code counts as code too, important bits tested elsewhere. 

The important part of the validations i.e. logic is already checked elsewhere so this is only testing a specific part of the form editor UI that is not very valuable by itself in my opinion. So the trade-off here is that we get more slow browser test code to maintain for a not so comprehensive browser level feature test of validations. If we broke the validations in the form editor UI a lot, we could add a more comprehensive browser test of form editor validations. However we are not at such a point yet. 

I see our browser tests as validating the (happy) paths of our most valuable use cases. And sometimes testing a really difficult part of the UI or something we break a lot.

2020-10-20 11:39 UTC, Macroz commented on test/clj/rems/test_browser.clj
> +        (btu/wait-visible {:tag :h1 :fn/has-text "Form"})))
I don't quite understand, aren't they are doing different things? The first one is checking that there is a value visible, the second will wait for a completely different heading.

2020-10-20 19:45 UTC, Macroz commented on test/clj/rems/test_browser.clj
> +        ;; (btu/scroll-and-click :fields-0-type-label)
I think it's not necessary to have a test for this. Or rather if there is one it should be in the CLJS tests.

2020-10-21 05:25 UTC, opqdonut commented on test/clj/rems/test_browser.clj
> +        ;; (btu/scroll-and-click :fields-0-type-label)
This sounds like a regression test for #2399. I'm not sure you can write one using just CLJS unit tests. I think changing the field type once in this test is a good idea to cover that path.

2020-10-21 05:31 UTC, Macroz commented on test/clj/rems/test_browser.clj
> +        ;; (btu/scroll-and-click :fields-0-type-label)
Yeah, sometimes a regression test is worthwhile but I would not write it as a regression test quite yet for this feature. Just saying there doesn't need to be one here yet.

2020-10-21 12:21 UTC, marharyta commented on test/clj/rems/test_browser.clj
> +          (btu/click-el (first buttons))
👍

2020-10-21 12:22 UTC, marharyta commented on test/clj/rems/test_browser.clj
> +        (let [buttons (btu/query-all {:tag :button :fn/has-class :info-button})]
I am not sure weather this is a nice to have or should do?

2020-10-27 16:37 UTC, marharyta commented
@Macroz Looks like I have addressed the issues

2020-10-28 12:06 UTC, marharyta commented on test/clj/rems/test_browser.clj
> +        (let [buttons (btu/query-all {:tag :button :fn/has-class :info-button})]
I think the best thing to do would be to go through this in a separate PR, I have created an issue to address it. https://github.com/CSCfi/rems/issues/2418

2020-10-28 12:06 UTC, marharyta commented on test/clj/rems/test_browser.clj
> +          (not (is (btu/visible? {:tag :div :fn/has-class :info-collapse}))))
done

2020-10-28 12:07 UTC, marharyta commented on test/clj/rems/test_browser.clj
> +          (not (is (btu/visible? {:tag :div :fn/has-text "Info text (FI)"}))))
done

2020-11-02 11:08 UTC, marharyta commented
ping @Macroz

2020-11-04 07:59 UTC, marharyta commented
ping @Macroz

2020-11-04 08:43 UTC, Macroz requested changes
I think there is a small bug here to fix and had a couple further questions. 

The error message block now looks now more like what I'd expect :+1:

2020-11-04 08:43 UTC, Macroz commented on test/clj/rems/test_browser.clj
> +          (not (is (btu/visible? {:tag :div :fn/has-class :info-collapse})))
This should be `(is (not ...` and this will not work.

2020-11-04 08:43 UTC, Macroz commented on test/clj/rems/test_browser.clj
> +          (is (btu/visible? {:tag :label :class :application-field-label :fn/has-text "Option list (EN)"}))
If these were in the original place, there would be no need to read the diff here. These statements don't use the button at all?

2020-11-04 08:43 UTC, Macroz commented on test/clj/rems/test_browser.clj
> +          (is (not (btu/visible? {:tag :div :fn/has-class :info-collapse})))
These new asserts could really use some `(testing "info collapse can be toggled"` block(s) for description.

2020-11-04 08:43 UTC, Macroz commented on test/clj/rems/test_browser.clj
> +        (change-language :en)))
I think this looks odd with this line hanging here and this should be in the same block as above `change-language` statements. Also if you would check the language change while the field is still open you could remove extra click of the button.

2020-11-04 08:43 UTC, Macroz commented on test/clj/rems/test_browser.clj
> -        (btu/wait-visible {:tag :h1 :fn/text "Form"})
Why is this line removed?

2020-11-04 08:43 UTC, Macroz commented on test/clj/rems/test_browser.clj
> +        (btu/scroll-query-el (first (btu/query-all {:tag :label :class :application-field-label})) {"block" "center"})
Why does this need the scroll?

2020-11-04 08:43 UTC, Macroz commented on test/clj/rems/test_browser.clj
> +        (btu/scroll-query-el (first (btu/query-all {:tag :label :class :application-field-label})) {"block" "center"})
Even so you don't need to use the `-el` version to write this. It could be simply
`(btu/scroll-query {:class :application-field-label})`?

2020-11-17 12:16 UTC, marharyta commented
@Macroz @opqdonut is there something else I should add?

2020-11-17 12:19 UTC, opqdonut approved these changes
looks good to me

2020-11-17 12:19 UTC, opqdonut commented on test/clj/rems/test_browser.clj
> +        (btu/visible? {:tag :div :class :invalid-feedback :fn/has-text "Field \"Field description (optional)\" is required."})
hmm does it not show which language is missing? oh well, that can be fixed later/separately.

2020-11-17 12:19 UTC, opqdonut commented on CHANGELOG.md
> +- Added browser tests to the Field description collapsable element (#2346)
did you want to remove this?

2020-11-17 12:20 UTC, marharyta commented on CHANGELOG.md
> +- Added browser tests to the Field description collapsable element (#2346)
I will

2020-11-17 13:43 UTC, marharyta commented
@opqdonut should be done for now

2020-11-17 13:44 UTC, merged

2020-11-17 13:44 UTC, opqdonut commented on test/clj/rems/test_browser.clj
> -        (btu/wait-visible {:tag :h1 :fn/text "Form"})
moved lower